export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_TALENT_START = 'FETCH_TALENT_START';
export const FETCH_TALENT_SUCCESS = 'FETCH_TALENT_SUCCESS';
export const FETCH_TALENT_FAIL = 'FETCH_TALENT_FAIL';

export const FETCH_TALENT_CATEGORIES_START = 'FETCH_TALENT_CATEGORIES_START';
export const FETCH_TALENT_CATEGORIES_SUCCESS = 'FETCH_TALENT_CATEGORIES_SUCCESS';
export const FETCH_TALENT_CATEGORIES_FAIL = 'FETCH_TALENT_CATEGORIES_FAIL';

export const FETCH_SPOTLIGHT_CATEGORIES_START = 'FETCH_SPOTLIGHT_CATEGORIES_START';
export const FETCH_SPOTLIGHT_CATEGORIES_SUCCESS = 'FETCH_SPOTLIGHT_CATEGORIES_SUCCESS';
export const FETCH_SPOTLIGHT_CATEGORIES_FAIL = 'FETCH_SPOTLIGHT_CATEGORIES_FAIL';

export const FETCH_FAN_TALENT_FAVORITES_START = 'FETCH_FAN_TALENT_FAVORITES_START';
export const FETCH_FAN_TALENT_FAVORITES_SUCCESS = 'FETCH_FAN_TALENT_FAVORITES_START_SUCCESS';
export const FETCH_FAN_TALENT_FAVORITES_FAIL = 'FETCH_FAN_TALENT_FAVORITES_START_FAIL';

export const FETCH_NOTIFICATIONS_START = 'FETCH_NOTIFICATIONS_START';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAIL = 'FETCH_NOTIFICATIONS_FAIL';

export const BROWSE_SPOTLIGHT_CATEGORIES_START = 'BROWSE_SPOTLIGHT_CATEGORIES_START';
export const BROWSE_SPOTLIGHT_CATEGORIES_SUCCESS = 'BROWSE_SPOTLIGHT_CATEGORIES_SUCCESS';
export const BROWSE_SPOTLIGHT_CATEGORIES_FAIL = 'BROWSE_SPOTLIGHT_CATEGORIES_FAIL'

export const REMOVE_TALENT_FAVORITE_START = 'REMOVE_TALENT_FAVORITE_START';
export const REMOVE_TALENT_FAVORITE_SUCCESS = 'REMOVE_TALENT_FAVORITE_SUCCESS';
export const REMOVE_TALENT_FAVORITE_FAIL = 'REMOVE_TALENT_FAVORITE_FAIL';

export const SET_TALENT_IS_FAVORITE_START = 'SET_TALENT_IS_FAVORITE_START';
export const SET_TALENT_IS_FAVORITE_SUCCESS = 'SET_TALENT_IS_FAVORITE_SUCCESS';
export const SET_TALENT_IS_FAVORITE_FAIL = 'SET_TALENT_IS_FAVORITE_FAIL';

export const FETCH_ACCOUNT_START = 'FETCH_ACCOUNT_START';
export const FETCH_ACCOUNT_SUCCESS = 'FETCH_ACCOUNT_SUCCESS';
export const FETCH_ACCOUNT_FAIL = 'FETCH_ACCOUNT_FAIL';