export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const FETCH_TALENT_START = 'FETCH_TALENT_START';
export const FETCH_TALENT_SUCCESS = 'FETCH_TALENT_SUCCESS';
export const FETCH_TALENT_FAIL = 'FETCH_TALENT_FAIL';

export const FETCH_TALENT_CATEGORIES_START = 'FETCH_TALENT_CATEGORIES_START';
export const FETCH_TALENT_CATEGORIES_SUCCESS = 'FETCH_TALENT_CATEGORIES_SUCCESS';
export const FETCH_TALENT_CATEGORIES_FAIL = 'FETCH_TALENT_CATEGORIES_FAIL';

export const FETCH_SPOTLIGHT_CATEGORIES_START = 'FETCH_SPOTLIGHT_CATEGORIES_START';
export const FETCH_SPOTLIGHT_CATEGORIES_SUCCESS = 'FETCH_SPOTLIGHT_CATEGORIES_SUCCESS';
export const FETCH_SPOTLIGHT_CATEGORIES_FAIL = 'FETCH_SPOTLIGHT_CATEGORIES_FAIL';